const Blog = require('../models/Blog')

// Get all blogs
const getBlogs = async (req, res) => {
  try {
    const { page = 1, limit = 10, status, category, featured } = req.query

    const query = {}

    // For public access (no auth), only show published blogs
    // For admin access (with auth), show all or filter by status
    const isAuthenticated = req.headers.authorization

    if (!isAuthenticated) {
      query.status = 'published'
    } else {
      if (status) query.status = status
    }

    if (category) query.category = category
    if (featured !== undefined) query.featured = featured === 'true'

    const blogs = await Blog.find(query)
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(parseInt(limit))

    const total = await Blog.countDocuments(query)

    res.json({
      success: true,
      data: blogs,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      },
      total
    })
  } catch (error) {
    res.status(500).json({ success: false, message: error.message })
  }
}

// Get single blog by ID
const getBlog = async (req, res) => {
  try {
    const blog = await Blog.findById(req.params.id)

    if (!blog) {
      return res.status(404).json({ success: false, message: 'Blog not found' })
    }

    // Increment views
    await blog.incrementViews()

    res.json({ success: true, data: blog })
  } catch (error) {
    res.status(500).json({ success: false, message: error.message })
  }
}

// Get single blog by slug
const getBlogBySlug = async (req, res) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug })

    if (!blog) {
      return res.status(404).json({ success: false, message: 'Blog not found' })
    }

    // Increment views
    await blog.incrementViews()

    res.json({ success: true, data: blog })
  } catch (error) {
    res.status(500).json({ success: false, message: error.message })
  }
}

// Create blog
const createBlog = async (req, res) => {
  try {
    const blogData = {
      ...req.body
    }

    // Parse JSON fields if they're strings
    if (typeof blogData.author === 'string') {
      try {
        blogData.author = JSON.parse(blogData.author)
      } catch (e) {
        console.error('Error parsing author:', e)
      }
    }

    if (typeof blogData.tags === 'string') {
      try {
        blogData.tags = JSON.parse(blogData.tags)
      } catch (e) {
        console.error('Error parsing tags:', e)
      }
    }

    // Handle featured image if uploaded
    if (req.uploadedFiles && req.uploadedFiles.featuredImage) {
      blogData.featuredImage = req.uploadedFiles.featuredImage[0].url
    }

    // Slug will be auto-generated by the pre-save hook
    const blog = await Blog.create(blogData)

    res.status(201).json({
      success: true,
      message: 'Blog created successfully',
      data: blog
    })
  } catch (error) {
    console.error('Create blog error:', error)
    res.status(500).json({ success: false, message: error.message })
  }
}

// Update blog
const updateBlog = async (req, res) => {
  try {
    let blog = await Blog.findById(req.params.id)

    if (!blog) {
      return res.status(404).json({ success: false, message: 'Blog not found' })
    }

    const updateData = { ...req.body }

    // Parse JSON fields if they're strings
    if (typeof updateData.author === 'string') {
      try {
        updateData.author = JSON.parse(updateData.author)
      } catch (e) {
        console.error('Error parsing author:', e)
      }
    }

    if (typeof updateData.tags === 'string') {
      try {
        updateData.tags = JSON.parse(updateData.tags)
      } catch (e) {
        console.error('Error parsing tags:', e)
      }
    }

    // Handle featured image if uploaded
    if (req.uploadedFiles && req.uploadedFiles.featuredImage) {
      updateData.featuredImage = req.uploadedFiles.featuredImage[0].url
    }

    // Update blog
    Object.assign(blog, updateData)
    await blog.save() // This will trigger pre-save hooks for slug regeneration if title changed

    res.json({
      success: true,
      message: 'Blog updated successfully',
      data: blog
    })
  } catch (error) {
    console.error('Update blog error:', error)
    res.status(500).json({ success: false, message: error.message })
  }
}

// Delete blog
const deleteBlog = async (req, res) => {
  try {
    const blog = await Blog.findById(req.params.id)

    if (!blog) {
      return res.status(404).json({ success: false, message: 'Blog not found' })
    }

    await Blog.findByIdAndDelete(req.params.id)

    res.json({
      success: true,
      message: 'Blog deleted successfully'
    })
  } catch (error) {
    res.status(500).json({ success: false, message: error.message })
  }
}

// Get featured blogs
const getFeaturedBlogs = async (req, res) => {
  try {
    const { limit = 3 } = req.query
    const blogs = await Blog.getFeatured(parseInt(limit))

    res.json({
      success: true,
      count: blogs.length,
      data: blogs
    })
  } catch (error) {
    console.error('Get featured blogs error:', error)
    res.status(500).json({ success: false, message: error.message })
  }
}

// Create pending blog from API
const createPendingBlog = async (req, res) => {
  try {
    const {
      title,
      content,
      excerpt,
      featuredImage,
      category,
      author,
      tags
    } = req.body

    // Validate required fields
    if (!title || !content || !excerpt || !category || !author) {
      return res.status(400).json({
        success: false,
        message: 'Please provide all required fields'
      })
    }

    // Create blog with draft status and api source
    const blog = await Blog.create({
      title,
      content,
      excerpt,
      featuredImage,
      category,
      author,
      tags: tags || [],
      status: 'draft',
      source: 'api',
      isFeatured: false
    })

    res.status(201).json({
      success: true,
      message: 'Blog submitted for approval',
      data: {
        id: blog._id,
        title: blog.title,
        status: blog.status,
        source: blog.source
      }
    })
  } catch (error) {
    console.error('Create pending blog error:', error)
    res.status(500).json({
      success: false,
      message: 'Server error during blog submission',
      error: error.message
    })
  }
}

module.exports = {
  getBlogs,
  getBlog,
  getBlogBySlug,
  createBlog,
  updateBlog,
  deleteBlog,
  getFeaturedBlogs,
  createPendingBlog
}
